name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        run: ./scripts/buildprod.sh

      - name: Installing goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: DB Migration
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: ./scripts/migrateup.sh

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Push container to GCP AR
        run: gcloud builds submit --project notely-420416 --tag us-central1-docker.pkg.dev/notely-420416/notely-ar-repo/notely:latest .

      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image us-central1-docker.pkg.dev/notely-420416/notely-ar-repo/notely:latest --region us-central1 --allow-unauthenticated --project notely-420416 --max-instances=4

